config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :sessions, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #今回はadminなど他のスコープは使用せず、ログイン関係のパス名を変更したい為sessionsをskip（下記のscopeで定義）
    
  devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
    get "login", to: "users/sessions#new", as: :new_user_session
    post "login", to: "users/sessions#create", as: :user_session
    delete "logout", to: "users/sessions#destroy", as: :destroy_user_session
  end

  root 'products#index'
  
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end  
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      get '/products/:id', to: "products#change", as: :users_myproduct_change #要検討20191125
      delete '/products/:id', to: "products#destroy"
      patch '/products/:id', to: "products#update"
      get '/products/:id/edit', to: "products#sell_edit", as: :myedit
    end
    member do
      get 'logout'
      get 'profile'
      get 'credit_add'
      get 'credit_edit'
      get 'confirmation'
      get 'myaddress'
      get 'mail_pass'
      get 'tel'
      get 'myproducts_exhibiting'
      get 'myproducts_trading'
      get 'myproducts_sold'
    end
    resources :card, only: [:new] do
      collection do
        get 'show'
        post 'pay'
        post 'delete'
        get 'addition'
      end
    end
  end
  
  resources :signup, only: [:create] do 
    collection do
      get 'new'
      get 'user_registration1'
      get 'user_registration2'
      get 'user_registration3'
      get 'user_registration4'
      get 'done'
    end
  end

  namespace :api do
    resources :products, only: :create, defaults: { format: 'json'}
    resources :products2, only: :create, defaults: { format: 'json'}
    resources :products3, only: :create, defaults: { format: 'json'}
  end 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable
  has_many :products, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  has_one  :myaddress, dependent: :destroy
  accepts_nested_attributes_for :myaddress

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    sns_credential_record = SnsCredential.where(provider: auth.provider, uid: auth.uid)
    if user.present?
      unless sns_credential_record.present?
        SnsCredential.create(
          user_id: user.id,
          provider: auth.provider,
          uid: auth.uid
        )
      end
    elsif
      user = User.new(
        id: User.all.last.id + 1,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20],
        nickname: auth.info.name,
        last_name: auth.info.last_name,
        first_name: auth.info.first_name,
      )
      SnsCredential.new(
        provider: auth.provider,
        uid: auth.uid,
        user_id: user.id
      )
    end 
  user
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,255}\z/i
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  VALID_POSTAL_CODE = /\A\d{3}-?\d{4}\z/

  # user_registration1入力項目
  validates :nickname, presence: true, length: { maximum: 20 }, on: :validates_step1
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'は有効でありません。' }, on: :validates_step1
  validates :password, presence: true, length: { in: 7..255 }, format: { with: VALID_PASSWORD_REGEX, message: 'は255文字以下に設定して下さい'}, on: :validates_step1
  validates :birthday, presence: true, on: :validates_step1
  validates :last_name, presence: true, length: { maximum: 20 }, on: :validates_step1
  validates :first_name, presence: true, length: { maximum: 20 }, on: :validates_step1
  validates :last_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}, on: :validates_step1
  validates :first_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}, on: :validates_step1

  # user_registration2入力項目
  validates :tel, presence: true, format: { with: VALID_PHONE_REGEX, message: 'は有効でありません。'}, on: :validates_step2

  # user_registration3入力項目
  validates :last_name, presence: true, length: { maximum: 20 }, on: :validates_step3
  validates :first_name, presence: true, length: { maximum: 20 }, on: :validates_step3
  validates :last_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}, on: :validates_step3
  validates :first_name_kana, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい。'}, on: :validates_step3
  validates :zip, presence: true, length: { maximum: 8 }, format: { with: VALID_POSTAL_CODE, message: 'は有効でありません。' }, on: :validates_step3
  validates :city_name, presence: true, length: { maximum: 50 }, on: :validates_step3
  validates :block_name, presence: true, length: { maximum: 100 }, on: :validates_step3
  validates :bill_name, length: { maximum: 100 }, on: :validates_step3
  validates :tel, format: { with: VALID_PHONE_REGEX, message: 'は有効でありません。'}, allow_blank: true, on: :validates_step3

  # 下記の記述が無いと、devise機能によりemailとpasswordのバリデーションが抜けられない
  protected
  
  def password_required?
    # ステップ1のときだけバリデーションがかかるように条件分岐
    if validation_context == :user_registration1
      !persisted? || !password.nil? || !password_confirmation.nil?
    end
  end

  def email_required?
    # ステップ1のときだけバリデーションがかかるように条件分岐
    if validation_context == :user_registration1
      true
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to user_registration1_signup_index_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: 'google') if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"][:info]
      redirect_to user_registration1_signup_index_url
    end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def failure
    redirect_to root_path
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

    # GET /resource/sign_in
    def new
      super
    end
  
    # POST /resource/sign_in
    def create
      if verify_recaptcha
        super
      else
        self.resource = resource_class.new
        respond_with_navigational(resource) { render :new }
      end
    end
  
  # 下記元の記述

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user
  before_action :set_user, except:[:edit]
  before_action :set_myaddress, only:[:update, :myaddress]
  before_action :set_products, only: [:myproducts_exhibiting, :myproducts_trading, :myproducts_sold]

  def show
  end

  def edit
  end

  def update
# ストロングパラメータが片方nilだった場合、エラーを発生させるので、回避（requireメソッドの特徴)
    if params[:myaddress] == nil
      if @user.update(user_params)
        redirect_to user_path(@user)
        
      else
        redirect_to root_path
      end
    else params[:user] == nil
      if @myaddress.update(myaddress_params)
        redirect_to user_path(@user)
      else
        redirect_to root_path
      end
    end
  end

  def logout
  end

  def profile
  end

  def credit_add
    card = Card.where(user_id: current_user.id)
    redirect_to user_card_index_path(@user) if card.exists?
  end

  def credit_edit
  end
  
  def confirmation
  end

  def myaddress
  end

  def mail_pass
  end

  def tel
  end

  def myproducts_exhibiting
    @product = @products.where(status_id: "1").order("id DESC").limit(15)
  end

  def myproducts_trading
    @product = @products.where(status_id: "2").order("id DESC").limit(15)
  end

  def myproducts_sold
    @product = @products.where(status_id: "3").order("id DESC").limit(15)
  end

  # ログイン中ユーザーでなければ、他ユーザーのマイページは見れない
  def ensure_correct_user
    if current_user.id !=  params[:id].to_i
     redirect_to new_user_session_path
    else
      true
    end
  end


  private


  def user_params
    params.require(:user).permit(
      :nickname,
      :self_introduction,
      :zip,
      :prefecture,
      :city_name,
      :block_name,
      :bill_name,
      :tel,
      :email,
      :password
    )
  end

  def myaddress_params
    params.require(:myaddress).permit(
      :zip,
      :prefecture,
      :city_name,
      :block_name,
      :bill_name,
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :tel
    )
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_myaddress
    @myaddress = Myaddress.find_by(user_id: @user.id)
  end

  def set_products
    @products = Product.where(user_id: current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/section/_log-out.html.haml
.main__right-logout
  =link_to destroy_user_session_path, method: :delete, class: "main__right-logout-btn" do
    .main__right-logout-space
      ログアウト

app/views/users/section/_mail-pass-edit.html.haml
.signup-view-1page
  %section.signup-view-block
    %h2.signup-view-block__explanation 
      メール/パスワード
    = form_with model: @user, local: true do |f|
      .signup-view-block__form--top
        .signup-form1
          %label.signup-form1__label
            メールアドレス
          = f.email_field :email, placeholder: 'PC・携帯どちらでも可', class: 'signup-form1__form validate custom[email]'
          %p.mail-pass-explanation
            メールアドレスを変更すると確認メールが送信されます。メール内のURLをクリックすると変更完了です。
        .signup-form1
          %label.signup-form1__label
            現在のパスワード
          = f.password_field :password, class: 'signup-form1__form '
        .signup-form1
          %label.signup-form1__label
            新しいパスワード
          = f.password_field :password, placeholder: '6文字以上', class: 'signup-form1__form '
        .signup-form1
          %label.signup-form1__label
            新しいパスワード確認
          = f.password_field :password, placeholder: '6文字以上', class: 'signup-form1__form '
        .signup-form1
          %p.mail-pass-explanation
            パスワードを設定したい場合は上記をすべて入力してください。（設定しない場合は空欄）
        .signup-next-submit
          = f.submit '変更する'
        .mail-pass-white-space

app/views/users/section/_mypage-left.html.haml
.main__left
  .main__left-list
    =link_to user_path(@user), class: "main__left-list__nav btn space-1" do
      マイページ
      .select-icon-space
        =fa_icon 'angle-right', class: 'select-icon i1'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-2" do
      お知らせ
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i2'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-3" do
      やることリスト
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i3'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-4" do
      いいね！一覧
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i4'
  .main__left-list
    =link_to new_product_path, class: "main__left-list__nav btn space-5" do
      出品する
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i5'
  .main__left-list
    =link_to myproducts_exhibiting_user_path(@user), class: "main__left-list__nav btn space-6" do
      出品した商品 - 出品中
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i6'
  .main__left-list
    =link_to myproducts_trading_user_path(@user), class: "main__left-list__nav btn space-7" do
      出品した商品 - 取引中
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i7'
  .main__left-list
    =link_to myproducts_sold_user_path(@user), class: "main__left-list__nav btn space-8" do
      出品した商品 - 売却済み
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i8'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-9" do
      購入した商品 - 取引中
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i9'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-10" do
      購入した商品 - 過去の取引
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i10'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-11" do
      ニュース一覧
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i11'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-12" do
      評価一覧
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i12'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-13" do
      ガイド
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i13'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-14" do
      お問い合わせ
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i14'
  %h1.merupay
    メルペイ
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-15" do
      売上・振込申請
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i15'
  .main__left-list
    =link_to "#", class: "main__left-list__nav btn space-16" do
      ポイント
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i16'
  %h2.setting
    設定
  .main__left-list
    =link_to profile_user_path(@user), class: "main__left-list__nav btn space-17" do
      プロフィール
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i17'
  .main__left-list
    =link_to myaddress_user_path(@user), class: "main__left-list__nav btn space-18" do
      発送元・お届け先住所変更
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i18'
  .main__left-list
    =link_to credit_add_user_path(@user), class: "main__left-list__nav btn space-19" do
      支払い方法
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i19'
  .main__left-list
    =link_to mail_pass_user_path(@user), class: "main__left-list__nav btn space-20" do
      メール/パスワード
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i20'
  .main__left-list
    =link_to confirmation_user_path(@user), class: "main__left-list__nav btn space-21" do
      本人情報
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i21'
  .main__left-list
    =link_to tel_user_path(@user), class: "main__left-list__nav btn space-22" do
      電話番号の確認
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i22'
  .main__left-list
    =link_to logout_user_path(@user), class: "main__left-list__nav btn space-23" do
      ログアウト
      .select-icon-space
        = fa_icon 'angle-right', class: 'select-icon i23'
= javascript_include_tag 'user.js'

app/views/users/section/_myproducts-exhibiting.html.haml
.buy-product-mypage
  %p.buy-product-title-mypage
    出品した商品
.transaction-mypage
  =link_to "javascript:void(0)", class: "transaction-now-mypage transaction-tab-mypage btn active-2-mypage" do
    .border-red-2-mypage.line-up-2-mypage
    %p.transaction-now-title-mypage
      出品中
  =link_to myproducts_trading_user_path, class: "transaction-past-mypage2 transaction-tab-mypage btn" do
    %p.transaction-past-title-mypage
      取引中
  =link_to myproducts_sold_user_path, class: "transaction-past-mypage2 transaction-tab-mypage btn" do
    %p.transaction-past-title-mypage
      売却済み
.buy-products-now-list-mypage3.content-2.show-2-mypage
  .myproducts-list-block
    %ul.myproducts-list-block-ul
      - @product.each do |product|
        %li.myproducts-list-block-ul__box
          = link_to users_myproduct_change_users_path(product), class: "myproducts-list-block-ul__box--link" do
            %figure.myproducts-list-block-ul__box--link__figure
              = image_tag("#{product.images[0].image}", class:"myproducts-list-block-ul__box--link__figure__image")
            .myproducts-list-block-ul__box--link__title
              .myproducts-list-block-ul__box--link__title--name
                #{product.name}
              .myproducts-list-block-ul__box--link__title--exhibiting
                出品中
            = fa_icon 'angle-right', class: 'myproducts-select-icon'
      - if @product.empty?
        .myproducts-list-block-ul__nil-exhibiting

  %ul.mypage-products-arrow
    %li.mypage-products-arrow__left
      = link_to image_tag("/left.png", class:"mypage-products-arrow__left--icon")
    %li.mypage-products-arrow__right
      = link_to image_tag("/right.png", class:"mypage-products-arrow__right--icon")

app/views/users/section/_myproducts-sold.html.haml
.buy-product-mypage
  %p.buy-product-title-mypage
    出品した商品
.transaction-mypage
  =link_to myproducts_exhibiting_user_path, class: "transaction-now-mypage2 transaction-tab-mypage btn active-2-mypage" do
    %p.transaction-now-title-mypage
      出品中
  =link_to myproducts_trading_user_path, class: "transaction-past-mypage2 transaction-tab-mypage btn" do
    %p.transaction-past-title-mypage
      取引中
  =link_to "javascript:void(0)", class: "transaction-past-mypage transaction-tab-mypage btn" do
    .border-red-2-mypage.line-up-2-mypage
    %p.transaction-past-title-mypage
      売却済み
.buy-products-now-list-mypage3.content-2.show-2-mypage
  .myproducts-list-block
    %ul.myproducts-list-block-ul
      - @product.each do |product|
        %li.myproducts-list-block-ul__box
          = link_to users_myproduct_change_users_path(product), class: "myproducts-list-block-ul__box--link" do
            %figure.myproducts-list-block-ul__box--link__figure
              = image_tag("#{product.images[0].image}", class:"myproducts-list-block-ul__box--link__figure__image")
            .myproducts-list-block-ul__box--link__title
              .myproducts-list-block-ul__box--link__title--name
                #{product.name}
              .myproducts-list-block-ul__box--link__title--sold
                売却済
            = fa_icon 'angle-right', class: 'myproducts-select-icon'
      - if @product.empty?
        .myproducts-list-block-ul__nil-case

  %ul.mypage-products-arrow
    %li.mypage-products-arrow__left
      = link_to image_tag("/left.png", class:"mypage-products-arrow__left--icon")
    %li.mypage-products-arrow__right
      = link_to image_tag("/right.png", class:"mypage-products-arrow__right--icon")

app/views/users/section/_myproducts-trading.html.haml
.buy-product-mypage
  %p.buy-product-title-mypage
    出品した商品
.transaction-mypage
  =link_to myproducts_exhibiting_user_path, class: "transaction-now-mypage2 transaction-tab-mypage btn active-2-mypage" do
    %p.transaction-now-title-mypage
      出品中
  =link_to "javascript:void(0)", class: "transaction-past-mypage transaction-tab-mypage btn" do
    .border-red-2-mypage.line-up-2-mypage
    %p.transaction-past-title-mypage
      取引中
  =link_to myproducts_sold_user_path, class: "transaction-past-mypage2 transaction-tab-mypage btn" do
    %p.transaction-past-title-mypage
      売却済み
  .buy-products-now-list-trading.content-2.show-2-mypage
  .myproducts-list-block
.buy-products-now-list-mypage3.content-2.show-2-mypage
  .myproducts-list-block
    %ul.myproducts-list-block-ul
      - @product.each do |product|
        %li.myproducts-list-block-ul__box
          = link_to root_path, class: "myproducts-list-block-ul__box--link" do
            %figure.myproducts-list-block-ul__box--link__figure
              = image_tag("#{product.images[0].image}", class:"myproducts-list-block-ul__box--link__figure__image")
            .myproducts-list-block-ul__box--link__title
              .myproducts-list-block-ul__box--link__title--name
                #{product.name}
              .myproducts-list-block-ul__box--link__title--trading
                取引中
            = fa_icon 'angle-right', class: 'myproducts-select-icon'
      - if @product.empty?
        .myproducts-list-block-ul__nil-tranding

  %ul.mypage-products-arrow
    %li.mypage-products-arrow__left
      = link_to image_tag("/left.png", class:"mypage-products-arrow__left--icon")
    %li.mypage-products-arrow__right
      = link_to image_tag("/right.png", class:"mypage-products-arrow__right--icon")

app/views/users/section/_profile-edit.html.haml
.profile
  = form_with model: @user, local: true do |f|
    .profile-space
      %h1 プロフィール
    .profile-image
      = fa_icon 'smile-o', class: 'profile-icon'
      .name-place-holder
        = f.text_field :nickname, class: 'name-place-holder-field', value: "#{@user.nickname}", placeholder: '例）AYA☆セール中'
    .text-place-holder
      = f.text_field :self_introduction, class: 'text-place-holder-field', value: "#{@user.self_introduction}", placeholder: '例）こんにちは☆ご覧いただきありがとうございます！'
      %button{type: "submit", class: 'profile-btn'} 変更する

app/views/users/section/_tel-edit.html.haml
.signup-view-1page
  %section.signup-view-block
    %h2.signup-view-block__explanation 
      電話番号の確認

    = form_with model: @user, local: true do |f|
      .signup-tel-block
        .signup-tel-block__form
          %label.signup-tel-block__form--label
            携帯電話の番号
          = f.text_field :tel, value: "#{@user.tel}", placeholder: '携帯電話の番号を入力'
          本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        = f.submit 'SMSを送信する', class: "signup-tel-block__btn"
        %p.signup-tel-block__content
          ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        %p.signup-tel-block__text
          = link_to( "電話番号の確認が必要な理由〉", "/", class: "signup-tel-block__text--link")
        .mail-pass-white-space