config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :sessions, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #今回はadminなど他のスコープは使用せず、ログイン関係のパス名を変更したい為sessionsをskip（下記のscopeで定義）
    
  devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
    get "login", to: "users/sessions#new", as: :new_user_session
    post "login", to: "users/sessions#create", as: :user_session
    delete "logout", to: "users/sessions#destroy", as: :destroy_user_session
  end

  root 'products#index'
  
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end  
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      get '/products/:id', to: "products#change", as: :users_myproduct_change #要検討20191125
      delete '/products/:id', to: "products#destroy"
      patch '/products/:id', to: "products#update"
      get '/products/:id/edit', to: "products#sell_edit", as: :myedit
    end
    member do
      get 'logout'
      get 'profile'
      get 'credit_add'
      get 'credit_edit'
      get 'confirmation'
      get 'myaddress'
      get 'mail_pass'
      get 'tel'
      get 'myproducts_exhibiting'
      get 'myproducts_trading'
      get 'myproducts_sold'
    end
    resources :card, only: [:new] do
      collection do
        get 'show'
        post 'pay'
        post 'delete'
        get 'addition'
      end
    end
  end
  
  resources :signup, only: [:create] do 
    collection do
      get 'new'
      get 'user_registration1'
      get 'user_registration2'
      get 'user_registration3'
      get 'user_registration4'
      get 'done'
    end
  end

  namespace :api do
    resources :products, only: :create, defaults: { format: 'json'}
    resources :products2, only: :create, defaults: { format: 'json'}
    resources :products3, only: :create, defaults: { format: 'json'}
  end 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "show"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to controller: "signup", action: "user_registration4"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    @user = User.find(params[:user_id])
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to user_path(@user)
  end

  def show #Cardのデータをpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    @user = User.find(params[:user_id])
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def addition
    card = Card.where(user_id: current_user.id)
    @user = User.find(params[:user_id])
    redirect_to action: "show" if card.exists?
  end

end

app/views/card/addition.html.haml
= render 'layouts/header'

= render 'layouts/breadcrumbs'

.main
  = render partial: 'users/section/mypage-left'
  .main__right
    .signup-view-1page
      %section.signup-view-block
        %h2.signup-view-block__explanation 
          支払い方法
        = form_tag( pay_user_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class: "signup-view-block__form") do
          .signup-view-block__form--top
            .signup-form1
              %label.signup-form1__label
                カード番号
              %span.signup-form1__span
                必須
              = text_field_tag "number", "", class: "number signup-form1__form", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            .signup-form4
              .signup-form4-block
                %label.signup-form1__label
                  有効期限
                %span.signup-form1__span
                  必須
              .signup-form4__form
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span 月
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span 年
            .signup-form1
              = image_tag("/credit_card_logo.jpg",size: "189x49",class: "credit-image")
            .signup-form1
              %label.signup-form1__label
                セキュリティコード
              %span.signup-form1__span
                必須
              = text_field_tag "cvc", "", class: "cvc signup-form1__form", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            .signup-credit-form-label
              %span.credit-form-question ?
              = link_to( "カード裏面の番号とは？", "/", class: "credit-form-text")
            .signup-next-submit
              #card_token
                = submit_tag "追加する", id: "token_submit"


= render partial: '/layouts/exhibit-button'
= render 'layouts/footer'
= javascript_include_tag 'payjp.js'

app/views/card/new.html.haml
.user-container
  .user-container-header
    %h1.user-container-header__left
      =link_to root_path, class: "signup-home-link" do
        = image_tag("fmarket_logo_red.svg",size: "189x49",class: "image")
    %nav.user-signup-bar
      %ol.user-signup-bar-progress4
        %li.user-signup-bar-progress4__type
          会員情報
          .user-signup-bar-progress4__rod-red-first
        %li.user-signup-bar-progress4__type
          電場番号認証
          .user-signup-bar-progress4__rod-red
        %li.user-signup-bar-progress4__type
          お届け先住所入力
          .user-signup-bar-progress4__rod-red
        %li.user-signup-bar-progress4__type-red
          支払い方法
          .user-signup-bar-progress4__rod-red-middle
        %li.user-signup-bar-progress4__type
          完了
          .user-signup-bar-progress4__rod-last

  .signup-view-1page
    %section.signup-view-block
      %h2.signup-view-block__explanation 
        支払い方法
      = form_tag(pay_user_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class: "signup-view-block__form") do
        .signup-view-block__form--top
          .signup-form1
            %label.signup-form1__label
              カード番号
            %span.signup-form1__span
              必須
            = text_field_tag "number", "", class: "number signup-form1__form", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          .signup-form4
            .signup-form4-block
              %label.signup-form1__label
                有効期限
              %span.signup-form1__span
                必須
            .signup-form4__form
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
          .signup-form1
            = image_tag("/credit_card_logo.jpg",size: "189x49",class: "credit-image")
          .signup-form1
            %label.signup-form1__label
              セキュリティコード
            %span.signup-form1__span
              必須
            = text_field_tag "cvc", "", class: "cvc signup-form1__form", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          .signup-credit-form-label
            %span.credit-form-question ?
            = link_to( "カード裏面の番号とは？", "/", class: "credit-form-text")
          .signup-next-submit
            #card_token
              = submit_tag "追加する", id: "token_submit"
  
  = render "layouts/exhibit-footer"
= javascript_include_tag 'payjp.js'

app/views/card/show.html.haml
= render 'layouts/header' 

.main
  = render partial: 'users/section/mypage-left'
  .main__right
    .credit-space
      .credit-title
        支払い方法
      .credit-edit
        .credit-list
          %section.credit-list-title
            %h3.credit-list-text クレジットカード一覧
          %ul.credit-create-card
            %li.credit-detail
              .credit-card-display
                = image_tag("/IMG_visa-image.png", class: "credit-img")
                .credit-number ************#{@default_card_information.last4}
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
                = form_tag(delete_user_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                  %input{ type: "hidden", name: "card_id", value: "" }
                  %button.credit-send-button 削除する
        .credit-line
          =link_to "javascript:void(0)", class: "credit-method" do
            支払い方法について
            =fa_icon 'angle-right', class: 'credit-angle-right'

= render partial: '/layouts/exhibit-button'
= render 'layouts/footer'

= javascript_include_tag 'payjp.js'