config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :sessions, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #今回はadminなど他のスコープは使用せず、ログイン関係のパス名を変更したい為sessionsをskip（下記のscopeで定義）
    
  devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
    get "login", to: "users/sessions#new", as: :new_user_session
    post "login", to: "users/sessions#create", as: :user_session
    delete "logout", to: "users/sessions#destroy", as: :destroy_user_session
  end

  root 'products#index'
  
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end  
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      get '/products/:id', to: "products#change", as: :users_myproduct_change #要検討20191125
      delete '/products/:id', to: "products#destroy"
      patch '/products/:id', to: "products#update"
      get '/products/:id/edit', to: "products#sell_edit", as: :myedit
    end
    member do
      get 'logout'
      get 'profile'
      get 'credit_add'
      get 'credit_edit'
      get 'confirmation'
      get 'myaddress'
      get 'mail_pass'
      get 'tel'
      get 'myproducts_exhibiting'
      get 'myproducts_trading'
      get 'myproducts_sold'
    end
    resources :card, only: [:new] do
      collection do
        get 'show'
        post 'pay'
        post 'delete'
        get 'addition'
      end
    end
  end
  
  resources :signup, only: [:create] do 
    collection do
      get 'new'
      get 'user_registration1'
      get 'user_registration2'
      get 'user_registration3'
      get 'user_registration4'
      get 'done'
    end
  end

  namespace :api do
    resources :products, only: :create, defaults: { format: 'json'}
    resources :products2, only: :create, defaults: { format: 'json'}
    resources :products3, only: :create, defaults: { format: 'json'}
  end 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
 
  has_many :images , dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :status
  belongs_to :user

  validates :name,        length: { maximum: 40 }, presence: true, on: :create
  validates :name,        length: { maximum: 40 }, presence: true
  validates :description,     length: { maximum: 1000 }, presence: true, on: :create
  validates :description,     length: { maximum: 1000 }, presence: true
  validates :delivery_charged, presence: true, on: :create
  validates :delivery_charged, presence: true
  validates :delivery_days, presence: true, on: :create
  validates :delivery_days, presence: true
  validates :sales_status, presence: true, on: :create
  validates :sales_status, presence: true
  validates :delivery_way, presence: true, on: :create
  validates :delivery_way, presence: true
  validates :user_id, presence: true, on: :create
  validates :user_id, presence: true
  validates :category_id, presence: true, on: :create
  validates :price, presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }, on: :create
  validates :price, presence: true, numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validate :must_have_image

  def must_have_image
    if images.empty?
      errors.add("")
    end
  end
  

  enum sales_status:{
    '---':           0, #---
    unused:          1, #新品、未使用
    nearly_unused:   2, #未使用に近い
    not_injured:     3, #目立った傷や汚れなし
    bit_injured:     4, #やや傷や汚れあり
    injured:         5, #傷や汚れあり
    bad:             6,  #全体的に状態が悪い
  },_prefix: true

  enum delivery_charged:{
    '---':                      0,  #---
    shipping_fee_on_shipper:    1,  #送料込み（出品者負担）
    shipping_fee_on_receiver:   2,  #着払い（購入者負担）
  },_prefix: true

  enum delivery_way:{
    '---':                  0, #---
    kuroneko_yamato:        1, #クロネコヤマト
    yu_pack:                2, #ゆうパック
    yu_mail:                3, #ゆうメール
    rakuraku_mercari_bin:   10, #らくらくメルカリ便
    letter_pack:            11, #レターパック
    normal:                 12, #普通郵便（定型、定型外）
    clickpost:              13, #クリックポスト
  },_prefix: true

  enum delivery_days:{
    '---':      0,  #---
    days1_2:    1,  #1日~2日で発送
    days2_3:    2,  #2日~3日で発送
    days4_7:    3,  #4日~7日で発送
  },_prefix: true

end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController

  def create
    parent = Category.find(params[:id])
    @children = parent.children
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :change, :destroy, :edit]
  before_action :set_product, only: [:destroy, :change, :show, :edit, :ensure_correct_product, :sell_edit]
  before_action :set_category, only: [:show, :change]
  before_action :ensure_correct_product, except: [:index, :new, :show, :edit, :create]
  before_action :set_image, only: [:show, :change,:sell_edit]
  before_action :set_current_category_group, only: :sell_edit
  before_action :set_current_size_for_sell_edit, only: :sell_edit
  before_action :user_restriction, only: [:edit]

  


  def index
    @products = Product.all.order("id DESC").limit(10)
    @products_ladies = Product.where(category_id: 33..230).order("id DESC").limit(10)
    @products_mens = Product.where(category_id:245..388).order("id DESC").limit(10)
  end

  def new
    @product = Product.new
    @product.images.build
    @parent = Category.where(id: 1..13)
  end


  def show
    @products = Product.order("id DESC").limit(6)
    if user_signed_in?
      redirect_to  users_myproduct_change_users_path(@product) if @product.user_id == current_user.id
    end
  end

  def change
    @product = Product.find(params[:id])
  end

  def edit
    redirect_to root_path if @product.status_id == 3
    gon.product_price = @product.price
    gon.all_point = current_user.point
  end

  def sell_edit
    @parent_group = Category.where(id: 1..13)
    @product_fee = (@product.price * 0.1).round
    @product_profit = (@product.price * 0.9).round
  end

  def update 
    @product = Product.find(params[:id])
    if @product.update(product_params) 
      redirect_to users_myproduct_change_users_path(@product)
    else       
      redirect_to myedit_users_path(@product)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
    else
      redirect_to new_product_path
    end
  end
  
  def destroy
    if @product.destroy
      redirect_to myproducts_exhibiting_user_path(current_user)
    else
      flash[:notice] = '問題が発生して削除できませんでした'
      redirect_to root_path
    end
  end
  
  private

  def product_params
    params.require(:product)
            .permit(:description, :name, :price, :delivery_charged,
                    :prefecture_id, :delivery_days, :sales_status, :delivery_way, 
                    :category_id,
                    :brand,
                    :size_id,
                    images_attributes: [:image, :id])
          .merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
    if @product.size_id.present?
      @size = Size.find(@product.size_id)
    end
  end

  def set_category
    @grandchild = Category.find("#{@product.category_id}")
    @child = @grandchild.parent
    @parent = @child.parent
  end

  def set_image
    @image = @product.images.first
    @images = @product.images
  end

  def ensure_correct_product
    @product = Product.find(params[:id])
    redirect_to root_path if current_user.id !=  @product.user_id
  end

  def set_current_category_group
    @selected_grandson_category = Category.find(@product.category_id)
    @selected_child_category = @selected_grandson_category.parent
    @selected_parent_category = @selected_child_category.parent
    @grandchild_group = @selected_grandson_category.siblings
    @child_group = @selected_child_category.siblings
  end

  def set_current_size_for_sell_edit
    if @size.present?
      gon.selected_size = @size
      if @size.size_tag.present?
        @size_tag_group = Size.where(size_tag: @size.size_tag)
      elsif
        @size_tag_group = Size.where(id: 1..2)
      end
    elsif
      @size = Size.find(1)
      @size_tag_group = Size.where(id: 1..2)
      gon.selected_size = nil
    end
  end

  def user_restriction
    @product = Product.find(params[:id])
    redirect_to root_path if current_user.id == @product.user_id
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_category-chanel-products.html.haml
.category-products
  .category-products--new
    .category-products--new__introduction
      %h3#ladies.new-category 新着順
      =link_to "#", class: "more-read"  do
        もっと見る >
      .category-products--new__lists
        %ul.new-category__lists
          - @products.each do |product|
            %li.new-item
              .new-item__content
                =link_to product_path(product), class: "new-item-image" do
                  %figure.figure-container
                    - if product.status_id == 3
                      .sold-out
                      %p.sold-out-name SOLD
                    %figcaption.figure-container__figcaption
                      %span.figure-container__figcaption__span
                        = product.name
                    .figure-container__image
                      %span.figure-container__image__price
                        = " ¥ #{product.price.to_s(:delimited)}"
                      = image_tag("#{product.images[0].image}", class: "image-price")

app/views/products/_category-ladies-products.html.haml
.category-products
  .category-products--new
    .category-products--new__introduction
      %h3#ladies.new-category レディース新着アイテム
      =link_to "#", class: "more-read"  do
        もっと見る >
      .category-products--new__lists
        %ul.new-category__lists
          - @products_ladies.each do |product|
            %li.new-item
              .new-item__content
                =link_to product_path(product), class: "new-item-image" do
                  %figure.figure-container
                    - if product.status_id == 3
                      .sold-out
                      %p.sold-out-name SOLD
                    %figcaption.figure-container__figcaption
                      %span.figure-container__figcaption__span
                        = product.name
                    .figure-container__image
                      %span.figure-container__image__price
                        = " ¥ #{product.price.to_s(:delimited)}"
                      = image_tag("#{product.images[0].image}", class: "image-price")

app/views/products/_category-mens-products.html.haml
.category-products
  .category-products--new
    .category-products--new__introduction
      %h3#ladies.new-category メンズ新着アイテム
      =link_to "#", class: "more-read"  do
        もっと見る >
      .category-products--new__lists
        %ul.new-category__lists
          - @products_mens.each do |product|
            %li.new-item
              .new-item__content
                =link_to product_path(product), class: "new-item-image" do
                  %figure.figure-container
                    - if product.status_id == 3
                      .sold-out
                      %p.sold-out-name SOLD
                    %figcaption.figure-container__figcaption
                      %span.figure-container__figcaption__span
                        = product.name
                    .figure-container__image
                      %span.figure-container__image__price
                        = " ¥ #{product.price.to_s(:delimited)}"
                      = image_tag("#{product.images[0].image}", class: "image-price")

app/views/products/_category-products.html.haml
.category-products
  .category-products--new
    .category-products--new__introduction
      %h3#ladies.new-category レディース新着アイテム
      =link_to "#", class: "more-read"  do
        もっと見る >
      .category-products--new__lists
        %ul.new-category__lists
          - @products.each do |product|
            %li.new-item
              .new-item__content
                =link_to product_path(product), class: "new-item-image" do
                  %figure.figure-container
                    %figcaption.figure-container__figcaption
                      %span.figure-container__figcaption__span
                        = product.name
                    .figure-container__image
                      %span.figure-container__image__price
                        = " ¥ #{product.price.to_s(:delimited)}"
                      = image_tag("#{product.images[0].image}", class: "image-price")

app/views/products/_category-vuitton-products.html.haml
.category-products
  .category-products--new
    .category-products--new__introduction
      %h3#ladies.new-category ルイ・ヴィトン新着アイテム
      =link_to "#", class: "more-read"  do
        もっと見る >
      .category-products--new__lists
        %ul.new-category__lists
          - @products_ladies.each do |product|
            %li.new-item
              .new-item__content
                =link_to product_path(product), class: "new-item-image" do
                  %figure.figure-container
                    %figcaption.figure-container__figcaption
                      %span.figure-container__figcaption__span
                        = product.name
                    .figure-container__image
                      %span.figure-container__image__price
                        = " ¥ #{product.price.to_s(:delimited)}"
                      = image_tag("#{product.images[0].image}", class: "image-price")

app/views/products/_itembuy.html.haml
.itembuy-user-title
  %section.itembuy-user-profile__box
  %h2.itembuy-user-profile__head
    = link_to '/', class: 'itembuy-user-profile__head-name' do
      = @product.user.nickname
      さんのその他の出品



    .itembuy-user-parents
      %ul.itembuy-user-profile
        - @products.each do |product|
          %li.itembuy-user-profile__box
            =image_tag("#{product.images[0].image}", size: '220x220')
            .itembuy-user-profile__body
              %h3.itembuy-user-profile__name
                = product.name
              .itembuy-user-profile__num
                .itembuy-user-profile__price
                  = " ¥ #{product.price.to_s(:delimited)}"
.itembuy-user-title
  %section.itembuy-user-profile__box
  %h2.itembuy-user-profile__head
    = link_to root_path, class: 'itembuy-user-profile__head-name' do
      = @product.name
      その他の商品

    .itembuy-user-parents
      %ul.itembuy-user-profile
        - @products.each do |product|
          %li.itembuy-user-profile__box
            =image_tag("#{product.images[0].image}", size: '220x220')
            .itembuy-user-profile__body
              %h3.itembuy-user-profile__name
                = product.name
              .itembuy-user-profile__num
                .itembuy-user-profile__price
                  = " ¥ #{product.price.to_s(:delimited)}"

app/views/products/change.html.haml
= render 'layouts/header'

.main
  = render partial: 'users/section/mypage-change'
 
= render 'layouts/footer'
= javascript_include_tag 'itembuy-slider.js'

app/views/products/edit.html.haml
.purchase-confirmation

  = render "layouts/exhibit-header"

  %main.purchase-confirmation__main

    %section.purchase-confirmation__main__container
      %h2.purchase-confirmation__main__container__head.bold
        購入内容の確認
      %section.purchase-confirmation__main__container__buy-content
        .purchase-confirmation__main__container__buy-content__inner
          %h3.purchase-confirmation__main__container__buy-content__inner__image
            = image_tag("#{@product.images[0].image}", height: '64', width: '64')
          %p.purchase-confirmation__main__container__buy-content__inner__name.bold
            = @product.name

          .form-box-tempolary.form-hairu-yotei
            %p.form-box-tempolary__buy-price.bold 
              = "¥#{@product.price.to_s(:delimited)}"
              %span.form-box-tempolary__buy-price__shipping-fee.f14 
            %ul.form-box-tempolary__buy-accordion
              %li.form-box-tempolary__buy-accordion__accordion-parent
                .form-box-tempolary__buy-accordion__accordion-parent__accordion-toggle#acdn-button
                  ポイントを使う
                  = fa_icon 'chevron-down'
                %ul.form-box-tempolary__buy-accordion__accordion-parent__accordion-child#acdn-target
                  %li.bold 
                    = "所持ポイント: P#{current_user.point}"
                  %li.form-box-tempolary__buy-accordion__accordion-parent__accordion-child__form-group
                    .form-box-tempolary__buy-accordion__accordion-parent__accordion-child__form-group__radio-default
                      %label
                        %input{type:"radio", name:"point", class:"radiobuttomA", value:"0"}
                        ポイントを使わない
                    .form-box-tempolary__buy-accordion__accordion-parent__accordion-child__form-group__radio-default
                      %label
                        %input{type:"radio", name:"point", class:"radiobuttomB", value:"1"}
                        全てのポイントを使う
                        %br 
                        = "P#{current_user.point}"
                    .form-box-tempolary__buy-accordion__accordion-parent__accordion-child__form-group__radio-default
                      %label
                        %input{type:"radio", name:"point", class:"radiobuttomA", value:"2"}
                        一部のポイントを使う
                    %input{class: "form-box-tempolary__buy-accordion__accordion-parent__accordion-child__form-group__used-point", placeholder: "使うポイントを入力", type: "number", disabled: "disabled"}
                      
            %ul.form-box-tempolary__result-price
              %li.form-box-tempolary__result-price__row.bold
                .form-box-tempolary__result-price__row__buy-price-cell1
                  支払い金額
                .form-box-tempolary__result-price__row__buy-price-cell2
                  %span#data-buy-pay
                    = "¥#{@product.price.to_s(:delimited)}"
            %p.confirmation-error-text
              この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
          = link_to "購入する", product_purchase_index_path(@product.id), class: "form-box-tempolary__btm-default .bold"
      %div
       
      %section.purchase-confirmation__main__container__buy-user-info
        .purchase-confirmation__main__container__buy-user-info__inner 
          %h3.bold 配送先
          %address.buy-user-info-text 
            = current_user.myaddress.zip
            %br
            = current_user.myaddress.prefecture
            = current_user.myaddress.city_name
            = current_user.myaddress.block_name
            = current_user.myaddress.bill_name
            %br
            = current_user.myaddress.last_name
            = current_user.myaddress.first_name
            %p
            = link_to '#', class: "buy-user-info-fix" do
              %span
                変更する
              = fa_icon 'chevron-right'

      %section.purchase-confirmation__main__container__buy-user-info
        .purchase-confirmation__main__container__buy-user-info__inner.pay-method
          %h3.bold 支払い方法
          %p
          %figure
          %p.buy-user-info-text 
            クレカ情報
          = link_to '#', class: "buy-user-info-fix" do
            %span
              変更する
            = fa_icon 'chevron-right'

  = render "layouts/exhibit-footer"
= javascript_include_tag 'purchase-confirmation.js'

app/views/products/index.html.haml
= render 'layouts/header'
.main-top
  .slide-zone
    %section.slide-banner.owl-carousel
      = link_to "", root_path, class: "slide-banner__link slide-banner__link--natsukashi"
      = link_to "", root_path, class: "slide-banner__link slide-banner__link--new-life"
      = link_to "", root_path, class: "slide-banner__link slide-banner__link--bokurano-heisei"

  .popularity-bland
    %h2 ★最新商品★
    .popularity-bland__categories
      %ul.bland-lists

    = render 'products/category-chanel-products'

  .popularity-category
    %h2 人気のカテゴリー
    .popularity-category__categories
      %ul.category-lists
        %li.category-list
          =link_to '/#ladies', class: "link-category", id: "ladies" do
            レディース
        %li.category-list
          =link_to '/', class: "link-category" do
            メンズ
        %li.category-list
          =link_to '/', class: "link-category" do
            家電・スマホ・カメラ
        %li.category-list
          =link_to '/', class: "link-category" do
            おもちゃ・ホビー・グッズ
  

    = render 'products/category-ladies-products'
    = render 'products/category-mens-products'


  = render 'layouts/footer'
  = render partial: '/layouts/exhibit-button'

= javascript_include_tag 'owl-carousel.js'

app/views/products/show.html.haml
= render "layouts/header"
.itembuy-container
  %section.itembuy-content
    %h1.itembuy-content__name
      =@product.name
    .itembuy-content__clearfix
      .itembuy-content__photo
        .itembuy-content__auter
          .itembuy-content__owl-carousel
            - if @product.status_id == 3
              .sold-out
              %p.sold-out-name SOLD
            .owl-carousel-space
              =image_tag("#{@image.image}", class: 'owl-carousel-main show', size: '300x300')
            - @images[1..9].each do |image|
              =image_tag("#{image.image}", class: 'owl-carousel-main', size: '300x300')
        .itembuy-content__owl-carousel-thumb
          =image_tag("#{@image.image}", class: 'owl-carousel-sub active', size: '60x60')
        - @images[1..9].each do |image|
          =image_tag("#{image.image}", class: 'owl-carousel-sub', size: '60x60')
      %table.itembuy-content__table
        %tbody
          %tr
            %th 出品者
            %td
              = link_to "/", class: "user-nickname" do
                = @product.user.nickname
              %div
                .itembuy-content__ratings{ id: 'itembuy-icon-good' }
                  =fa_icon 'smile-o', class: 'icon-r'
                  %span 437
                .itembuy-content__ratings
                  =fa_icon 'meh-o', class: 'icon-y'
                  %span 4
                .itembuy-content__ratings
                  =fa_icon 'frown-o', class: 'icon-b'
                  %span 0
          %tr
            %th カテゴリー
            %td
              = link_to "#{@parent.name}", "#", class: "parent-category"
              %br
              = link_to "＞#{@child.name}", "#", class: "child-category"
              %br
              = link_to "＞#{@grandchild.name}", "#", class: "grandchild-category"
          %tr
            %th  ブランド
            %td
              = link_to "#{@product.brand}", "#", class: "brand-link"
          %tr
            %th 商品のサイズ
            %td
              %span 
                - if @size.present?
                  = @size.size_name
          %tr
            %th 商品の状態
            %td
              %span 
              = @product.sales_status_i18n
          %tr
            %th 配送料の負担
            %td
              %span
                = @product.delivery_charged_i18n
          %tr
            %th 配送の方法
            %td
              %span
                = @product.delivery_way_i18n
          %tr
            %th 配送元地域
            %td
              %span
              = link_to "#{@product.prefecture.name}", "#", class: "area-link"
          %tr
            %th 発送日の目安
            %td
              %span
                = @product.delivery_days_i18n
    .itembuy-content__price
      %span.itembuy-content__bold<
        = "¥#{@product.price.to_s(:delimited)}"
      %span.itembuy-content__tax (税込)
      %span.itembuy-content__fee 送料込み
      - if @product.status_id == 1
        = link_to edit_product_path, class: "itembuy-price-box" do
          購入画面に進む
      - elsif @product.status_id == 3
        .sold-out-btn
          %p.sold-out-name2 売り切れました
    .itembuy-detail
      %p.itembuy-detail__inner
        =@product.description
    .itembuy-button
      .itembuy-button__left
        =link_to "#", class: "new-item-image" do
          %button
            = fa_icon 'heart-o', class: 'icon-g'
            %span
              いいね! ０
      .itembuy-button__left__report
        =link_to "#", class: "new-item-image" do
          %button 
            =fa_icon 'flag-o', class: 'icon-g'
            %span 
              不適切な商品の報告
      .itembuy-button__right
        =link_to "#", class: "new-item-image" do
          %button
            =fa_icon 'shopping-bag', class: 'icon-b'
            %span
              あんしん・あんぜんへの取り組み
.itembuy-content-box
  .itembuy-detail-message
    .itembuy-content__comment
      %form.itembuy-message__form
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea
      - if @product.status_id == 1
        %button
          %span 
            コメントする
      - elsif @product.status_id == 3
        .sold-out-btn2
          %p.sold-out-name2 売り切れのためコメントできません
        .itembuy-nav
          .itembuy-nav__left
            = fa_icon 'chevron-left', class: 'icon-g'
            = link_to "","#"
          .itembuy-nav__right
            = link_to "","#"
            = fa_icon 'chevron-right', class: 'icon-g'
  .itembuy-media-box
    %ul.itembuy-media-box__list
      %li
        =link_to '/' do
          = fa_icon 'facebook-square', class: 'icon-facebook'
      %li
        =link_to '/' do
          = fa_icon 'twitter-square', class: 'icon-twitter'
      %li
        =link_to '/' do
          = fa_icon 'pinterest-square', class: 'icon-pinterest'
  = render "products/itembuy"
= render "layouts/footer"

= javascript_include_tag 'itembuy-slider.js'