config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :sessions, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #今回はadminなど他のスコープは使用せず、ログイン関係のパス名を変更したい為sessionsをskip（下記のscopeで定義）
    
  devise_scope :user do #ログイン関係のパス名をloginとlogoutに変更
    get "login", to: "users/sessions#new", as: :new_user_session
    post "login", to: "users/sessions#create", as: :user_session
    delete "logout", to: "users/sessions#destroy", as: :destroy_user_session
  end

  root 'products#index'
  
  resources :products do
    resources :purchase, only: [:index] do
      collection do
        post 'pay'
        get 'done'
      end
    end  
  end

  resources :users, only: [:show, :edit, :update] do
    collection do
      get '/products/:id', to: "products#change", as: :users_myproduct_change #要検討20191125
      delete '/products/:id', to: "products#destroy"
      patch '/products/:id', to: "products#update"
      get '/products/:id/edit', to: "products#sell_edit", as: :myedit
    end
    member do
      get 'logout'
      get 'profile'
      get 'credit_add'
      get 'credit_edit'
      get 'confirmation'
      get 'myaddress'
      get 'mail_pass'
      get 'tel'
      get 'myproducts_exhibiting'
      get 'myproducts_trading'
      get 'myproducts_sold'
    end
    resources :card, only: [:new] do
      collection do
        get 'show'
        post 'pay'
        post 'delete'
        get 'addition'
      end
    end
  end
  
  resources :signup, only: [:create] do 
    collection do
      get 'new'
      get 'user_registration1'
      get 'user_registration2'
      get 'user_registration3'
      get 'user_registration4'
      get 'done'
    end
  end

  namespace :api do
    resources :products, only: :create, defaults: { format: 'json'}
    resources :products2, only: :create, defaults: { format: 'json'}
    resources :products3, only: :create, defaults: { format: 'json'}
  end 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['users', 'show']
  - breadcrumb :user_show

- when ['users', 'profile']
  - breadcrumb :user_profile


- when ['users', 'credit_edit']
  - breadcrumb :user_credit_edit

- when ['users', 'confirmation']
  - breadcrumb :user_confirmation

- when ['users', 'myaddress']
  - breadcrumb :user_myaddress

- when ['users', 'mail_pass']
  - breadcrumb :user_mail_pass

- when ['users', 'tel']
  - breadcrumb :user_tel

- when ['users', 'logout']
  - breadcrumb :user_logout

- when ['users', 'myproducts_exhibiting']
  - breadcrumb :user_myproducts_exhibiting

- when ['users', 'myproducts_trading']
  - breadcrumb :user_myproducts_trading

- when ['users', 'myproducts_sold']
  - breadcrumb :user_myproducts_sold

= breadcrumbs separator: ' &nbsp;>&nbsp;&nbsp;',class: 'bread-crumbs'

app/views/layouts/_exhibit-button.html.haml
- if user_signed_in?
  =link_to  new_product_path, class: "exhibit-btn" do
    %p.exhibit-name
      出品
    = fa_icon 'camera', class: 'exhibit-icon'
- else
  =link_to  new_user_session_path, class: "exhibit-btn" do
    %p.exhibit-name
      出品
    = fa_icon 'camera', class: 'exhibit-icon'

app/views/layouts/_exhibit-footer.html.haml
.exhibitfooter
  .exhibitfooter__content
    = link_to("プライバシーポリシー", "＃")  
    = link_to("メルカリ利用規約", "＃") 
    = link_to("特定商取引に関する表記", "＃")
    %br
    %br
    %br
    %br
    =link_to root_path, class: "home-link" do
      = image_tag("logo_gray.svg",size: "80x65",class: "image")
    %br
    %br
    © 2020 Fmarket

app/views/layouts/_exhibit-header.html.haml
.exhibitheader
  =link_to root_path, class: "home-link" do
    = image_tag("fmarket_logo_red.svg",size: "189x49",class: "")

app/views/layouts/_flash_messages.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

app/views/layouts/_footer.html.haml
.footer
  .footer__top
    = image_tag("/footer-image-create.jpeg", class: "footer__top-image")
  .footer__bottom
    .footer__bottom-about
      .footer__bottom-about-merukari
        %p.merukari
          メルカリについて
        =link_to "会社概要（運営会社）", "#", class: "merukari-detail"
        =link_to "採用情報", "#", class: "merukari-detail"
        =link_to "プレスリリース", "#", class: "merukari-detail"
        =link_to "公式ブログ", "#", class: "merukari-detail"
        =link_to "メルカリロゴ利用ガイドライン", "#", class: "merukari-detail"
        =link_to "#", class: "merukari-icon-twitter" do
          = fa_icon 'twitter', class: 'twitter-icon'
        =link_to "#", class: "merukari-icon-facebook" do
          = fa_icon 'facebook-square', class: 'facebook-icon'
      .footer__bottom-about-help
        %p.help
          ヘルプ＆ガイド
        =link_to "らくらくメルカリ便", "#", class: "help-detail"
        =link_to "ゆうゆうメルカリ便", "#", class: "help-detail"
        =link_to "大型メルカリ便", "#", class: "help-detail"
        =link_to "車体取引ガイド", "#", class: "help-detail"
        =link_to "メルカリあんしん・あんぜん宣言！", "#", class: "help-detail"
        =link_to "偽ブランド品撲滅への取り組み", "#", class: "help-detail"
        =link_to "メルカリボックス", "#", class: "help-detail"
      .footer__bottom-about-privacy
        %p.privacy
          プライバシーと利用規約
        .footer__bottom-about-privacy__left
          =link_to "プライバシーポリシー", "#", class: "privacy-left-detail"
          =link_to "メルカリ利用規約", "#", class: "privacy-left-detail"
          =link_to "あんしんスマホサポート制度に関する利用特約", "#", class: "privacy-left-detail"
          =link_to "コンプライアンスポリシー", "#", class: "privacy-left-detail"
        .footer__bottom-about-privacy__right
          =link_to "個人データの安全管理に係る基本方針", "#", class: "privacy-right-detail"
          =link_to "特定商取引に関する表記", "#", class: "privacy-right-detail"
          =link_to "資金決済法に基づく表示", "#", class: "privacy-right-detail"
          =link_to "法令順守と犯罪抑止のために", "#", class: "privacy-right-detail"
      .footer__bottom-about-country
        %p.country
          国
        =link_to "国", "#", class: "country-detail"
        =link_to "United States", "#", class: "country-detail"
    .footer__bottom-company
      =link_to "#", class: "mercari-logo" do
        = image_tag("fmarket_logo_red.svg", class: "footer__bottom-image")
      %p.merukari-establish
        @ 2020 Fmarket

app/views/layouts/_header.html.haml
.header
  .header__container 
    .header__container__top
      .header__container__top__logo
        =link_to '/', class:"logo-link" do
          =image_tag("fmarket_logo_red.svg", class: "image-logo")
      %form.search-form{:action => "/jp/search/"}
        %input{:name => "keyword", :placeholder => "何かお探しですか？", :type => "search", :class => "search-box"}
          .search-icon= fa_icon 'search' 
    .header__container__bottom
      .header__container__bottom__left
        .header__container__bottom__left__category
          =link_to '/', class: "link-category" do
            カテゴリーから探す
            =fa_icon 'list-ul '
        .header__container__bottom__left__bland
          =link_to '/', class: "link-bland" do
            ブランドから探す
            =fa_icon 'tags'
      .header__container__bottom__right
        - if user_signed_in?
          %ul.user-lists 
            %li.user-list
              =link_to '#', class: "user-list__contents" do
                =fa_icon 'heart'
                いいね！一覧
            %li.user-list
              =link_to '#', class: "user-list__contents" do
                =fa_icon 'bell'
                お知らせ
            %li.user-list
              =link_to '#', class: "user-list__contents" do
                =fa_icon 'check'
                やることリスト
            %li.user-list
              =link_to user_path(current_user.id), class: "user-list__contents" do
                =fa_icon 'user-circle'
                マイページ
        - else
          .header__container__bottom__right__sign-up
            =link_to "新規会員登録", signup_index_path, class: "sign-up-btn" 
          .header__container__bottom__right__sign-in
            =link_to "ログイン", new_user_session_path, class: "sign-in-btn" 

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{content: "text/html: charset=UTF-8", "http-equiv": "Content-Type"}/
    %title FREEMARKET
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
 
  %body


   
    = yield